camera_id: CAM_TEST_01
config_version: cfg_v2
timezone: Asia/Ho_Chi_Minh
source: assets/speed1.mp4
imgsz: 1280
model:
  weights: weights/best_15thg9.onnx
  conf: 0.6
  imgsz: 1280
  classes:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  tracker: ocsort.yaml
  device: null
polygons:
- id: POLY_1
  kind: directional
  polygon:
  - - 774
    - 389
  - - 908
    - 389
  - - 758
    - 1003
  - - 27
    - 1003
  - - 363
    - 731
  - - 535
    - 586
  - - 693
    - 458
  - - 774
    - 390
  lines: []
  handler:
  - wrong_way
  - no_uturn
  rules:
    wrong_way:
      enable: false
    no_uturn:
      enable: false
    no_entry_road:
      enable: false
    no_parking:
      enable: false
    red_light_running:
      enable: false
    stop_line_violation:
      enable: false
    speeding:
      enable: true
  homography:
    src:
    - - 776
      - 389
    - - 906
      - 390
    - - 758
      - 999
    - - 31
      - 1003
    dst:
    - - 0.0
      - 0.0
    - - 7.5
      - 0.0
    - - 7.5
      - 30.0
    - - 0.0
      - 30.0
    measured_at: '2026-09-17T15:29:51'
  road_dir:
  - -0.5682339311347404
  - 0.8228670606526666
- id: POLY_2
  kind: directional
  polygon:
  - - 1074
    - 1003
  - - 1774
    - 1003
  - - 1546
    - 801
  - - 1346
    - 623
  - - 1207
    - 497
  - - 1103
    - 406
  - - 959
    - 399
  - - 988
    - 549
  - - 1020
    - 702
  - - 1047
    - 856
  - - 1076
    - 1003
  lines: []
  handler:
  - wrong_way
  - no_uturn
  rules:
    wrong_way:
      enable: false
    no_uturn:
      enable: false
    no_entry_road:
      enable: false
    no_parking:
      enable: false
    red_light_running:
      enable: false
    stop_line_violation:
      enable: false
    speeding:
      enable: true
  homography:
    src:
    - - 1078
      - 1003
    - - 1772
      - 1003
    - - 1104
      - 408
    - - 961
      - 401
    dst:
    - - 0.0
      - 0.0
    - - 7.5
      - 0.0
    - - 7.5
      - 30.0
    - - 0.0
      - 30.0
    measured_at: '2026-09-17T15:30:45'
  road_dir:
  - -0.5582113676108285
  - -0.8296987821312314
lines:
- id: L1
  p1:
  - 539
  - 581
  p2:
  - 854
  - 608
  allowed_sign: 1
- id: L2
  p1:
  - 1001
  - 602
  p2:
  - 1320
  - 594
  allowed_sign: -1
uturn_pairs: []
wrong_way:
  min_hits: 3
  min_reverse_frames: 5
  min_reverse_px: 60.0
  cooldown_s: 10.0
no_uturn:
  min_hits: 3
  cooldown_s: 10.0
no_entry_road:
  dwell_s: 2.0
  min_hits: 3
  cooldown_s: 10.0
evidence:
  dir: evidence
  jpeg_quality: 90
  retention_days: 7
signals: []
