lines: []
uturn_pairs: []
model:
  weights: weights/best.pt
  conf: 0.4
  imgsz: 640
  # Data custom data_v1 (best.pt): full 0-7 day/night, chua detect nguoi
  classes: [0, 1, 2, 3, 4, 5, 6, 7]
  tracker: ocsort.yaml
  device: null
polygons:
- id: POLY_1
  kind: directional
  polygon:
  - - 809
    - 441
  - - 928
    - 442
  - - 1427
    - 967
  - - 847
    - 967
  - - 811
    - 444
  lines: []
  handler:
  - wrong_way
  - no_uturn
  uturn_pairs: []
  homography:
    src:
    - - 823
      - 450
    - - 924
      - 453
    - - 1394
      - 953
    - - 867
      - 950
    dst:
    - - 0.0
      - 0.0
    - - 3.5
      - 0.0
    - - 3.5
      - 30.0
    - - 0.0
      - 30.0
    measured_at: '2026-09-11T10:32:18'
  road_dir:
  - -0.4675740685814222
  - -0.8839538960772872
